version: "3.9"

services:
  dispatcher:
    image: fteychene/cloud-cadavre-exquis-dispatcher:1.0-SNAPSHOT
    environment:
      REGISTER_URLS: "http://register:8080"
    networks:
      - cadaver
      - provider
  lb:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - cadaver
      - provider
  register:
    image: fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT
    depends_on:
      - postgres
    environment:
      POSTGRESQL_ADDON_HOST: "postgres"
      POSTGRESQL_ADDON_PORT: "5432"
      POSTGRESQL_ADDON_DB: "register"
      POSTGRESQL_ADDON_USER: "test"
      POSTGRESQL_ADDON_PASSWORD: "password"
    networks:
      - cadaver
      - provider
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "register"
    networks:
      - provider
networks:
  cadaver:
  provider: